version: '3'

services:
  app:
    container_name: app
    build:
      context: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7
    platform: linux/x86_64
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
